# Generated by Django 5.2.2 on 2025-06-05 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=255, unique=True)),
                ('trading_numbers', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('additional_name', models.TextField()),
                ('product_status', models.CharField(max_length=255)),
                ('specifications', models.TextField()),
                ('product_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.productgroup')),
            ],
        ),
    ]
